CREATE DATABASE IF NOT EXISTS dominos;
USE dominos;

CREATE TABLE pizzas(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
description VARCHAR(255) NOT NULL,
size VARCHAR(50) NOT NULL,
weight DOUBLE NOT NULL,
price DOUBLE NOT NULL,
image_url VARCHAR(255) NOT NULL
);

/* CATEGORY -> CHEESE, MEAT, VEGETABLES, SPICES, ADDITIONAL SAUCES(ONLY 3) */
CREATE TABLE ingredients(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
category VARCHAR(50) NOT NULL, 
price DOUBLE NOT NULL
);

CREATE TABLE pizza_ingredients(
pizza_id INT NOT NULL,
ingredient_id INT NOT NULL,
CONSTRAINT FOREIGN KEY(pizza_id) REFERENCES pizzas(id),
CONSTRAINT FOREIGN KEY(ingredient_id) REFERENCES ingredients(id),
CONSTRAINT PRIMARY KEY(pizza_id, ingredient_id)
);

/* CATEGORY -> DRINKS, DESSERTS, SAUCES */
CREATE TABLE non_pizzas(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
category VARCHAR(50) NOT NULL,
price DOUBLE NOT NULL,
quantity DOUBLE NOT NULL,
image_url VARCHAR(255) NOT NULL
);

CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL,
phone VARCHAR(50) NOT NULL,
city VARCHAR(50) NOT NULL,
street VARCHAR(50) NOT NULL
);

CREATE TABLE addresses(
id INT AUTO_INCREMENT PRIMARY KEY,
city VARCHAR(50) NOT NULL,
street VARCHAR(50) NOT NULL,
user_id INT NOT NULL,
CONSTRAINT FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE orders(
id INT AUTO_INCREMENT PRIMARY KEY,
total_sum DOUBLE NOT NULL,
order_time DATETIME NOT NULL,
delivery_time DATETIME NOT NULL,
status VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS restaurants;
CREATE TABLE restaurants(
id INT AUTO_INCREMENT PRIMARY KEY,
city VARCHAR(50) NOT NULL,
address VARCHAR(100) NOT NULL
);

ALTER TABLE orders
ADD COLUMN user_id INT NOT NULL,
ADD COLUMN restaurant_id INT NOT NULL,
ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES users(id),
ADD CONSTRAINT FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);

CREATE TABLE pizza_orders(
pizza_id INT NOT NULL,
order_id INT NOT NULL,
CONSTRAINT FOREIGN KEY(pizza_id) REFERENCES pizzas(id),
CONSTRAINT FOREIGN KEY(order_id) REFERENCES orders(id),
CONSTRAINT PRIMARY KEY(pizza_id, order_id)
);

CREATE TABLE non_pizza_orders(
non_pizza_id INT NOT NULL,
order_id INT NOT NULL,
CONSTRAINT FOREIGN KEY(non_pizza_id) REFERENCES non_pizzas(id),
CONSTRAINT FOREIGN KEY(order_id) REFERENCES orders(id),
CONSTRAINT PRIMARY KEY(non_pizza_id, order_id)
);